---
language: python
services: docker
python:
  - "3.8"

install:
  # Install test dependencies.
  - pip install -r requirements.txt

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
