---
- name: Install ZSH
  community.genera..homebrew:
    name: zsh
- name: Install ZSH Completions
  community.general.homebrew:
    name: zsh-completions
- name: Ensure /usr/local/bin/zsh is added to /etc/shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/zsh
  become: true
