---
- name: Include specific operating system installation instructions
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"
- name: Get path to ZSH
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: no
  check_mode: no
- name: Switch to zsh (Mac)
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  when:
    - "'USER' in ansible_env"
    - ansible_distribution == 'MacOSX'
  become: yes
- name: Switch to zsh (Linux)
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  when:
    - "'USER' in ansible_env"
    - ansible_distribution != 'MacOSX'
