---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: focal
    image: ubuntu:20.04
  - name: jammy
    image: ubuntu:22.04
  - name: noble
    image: ubuntu:24.04
provisioner:
  name: ansible
  inventory:
    host_vars:
      focal:
        zsh_completions_deb_url: >-
          https://download.opensuse.org/repositories/shells:
            /zsh-users:/zsh-completions/xUbuntu_19.10/amd64/
            zsh-completions_0.31.0+1.1_amd64.deb
verifier:
  name: testinfra
