---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: jammy
    image: ubuntu:22.04
  - name: noble
    image: ubuntu:24.04
provisioner:
  name: ansible
verifier:
  name: testinfra
